name = "Testing 3.2 Power Machines Extended"
author = "Dartis_Xui"
version = "1/0/0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bd69facb3cb7b148d1db469d01d15c6f1a4c3868b214463de302e70e5eb2516"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
