name = "Testing 3.2 Power Machines Extended"
author = "Dartis_Xui"
version = "1/0/0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7769ff37a0aa90eaa86f43c89a90ce8b452c259fe8004afb90691a9f2b9a42f"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
