name = "Testing 3.2 Power Machines Extended"
author = "Dartis_Xui"
version = "1/0/0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a4f5da89da3d0b79038c9e2641f893507d343ff1f5ddac19013bb9fc6339b81"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
